name: tbd
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.2.0
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  ionicons: ^0.2.2
  json_annotation: ^4.7.0
  loading_overlay: ^0.3.0
  logger: ^1.1.0
  permission_handler: ^10.2.0
  riverpod_annotation: ^1.2.1
  riverpod_generator: ^1.1.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.5.3
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
